name: fleet_app
description: "A new mobile application for Dire Dawa University's fleet management system."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  google_maps_flutter: ^2.5.3
  google_maps_flutter_android: ^2.6.2
  google_maps_flutter_platform_interface: ^2.4.3
  flutter_launcher_icons: ^0.13.1
  geolocator: ^10.1.0
  intl: ^0.19.0
  timeago: ^3.5.0
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  google_sign_in: ^6.1.6
  firebase_core_platform_interface: ^5.0.0
  firebase_storage: ^11.5.6

  # Firebase Web
  firebase_core_web: ^2.10.0
  firebase_auth_web: ^5.8.12
  cloud_firestore_web: ^3.8.10
  firebase_messaging_web: ^3.5.17
  firebase_analytics_web: ^0.5.5+16
  firebase_storage_web: ^3.6.7

  # State Management
  provider: ^6.1.1 

  # Maps & Location
  google_maps_flutter_web: ^0.5.4+2
  geolocator_web: ^2.2.0

  # UI Components
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  easy_localization: ^3.0.3

  # Utils
  uuid: ^4.2.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

  # JS
  js: ^0.7.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/DDU_LOGO.webp"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/DDU_LOGO.webp"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
    - assets/images/google_logo.png
