name: fleet_app
description: "A new mobile application for Dire Dawa University's fleet management system."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  google_maps_flutter: ^2.5.3
  geolocator: 13.0.4
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_messaging: ^14.6.5
  firebase_analytics: ^10.4.4

  # Firebase Web
  firebase_core_web: ^2.7.0
  firebase_auth_web: ^5.6.2
  cloud_firestore_web: ^3.6.3
  firebase_messaging_web: ^3.5.4
  firebase_analytics_web: ^0.5.4+4

  # State Management
  provider: ^6.1.1 

  # Maps & Location
  google_maps_flutter_web: ^0.5.4+2
  geolocator_web: ^4.1.3

  # UI Components
  fl_chart: ^0.70.2
  google_fonts: ^6.1.0
  easy_localization: ^3.0.3

  # Utils
  uuid: ^4.2.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
