// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPpusO-fXsjoD9AySj5Zha5pdl_C1WOIQ',
    appId: '1:777323726561:web:e0f42450dc5a05ba0f19a0',
    messagingSenderId: '777323726561',
    projectId: 'fleet-managment-7a764',
    authDomain: 'fleet-managment-7a764.firebaseapp.com',
    storageBucket: 'fleet-managment-7a764.firebasestorage.app',
    measurementId: 'G-F1RE8PRZLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIgxPUiNvcs4KQIpPSlqRQN_IObnpb8_M',
    appId: '1:777323726561:android:14e690b665a8e66a0f19a0',
    messagingSenderId: '777323726561',
    projectId: 'fleet-managment-7a764',
    storageBucket: 'fleet-managment-7a764.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsRPHOES5Zfpl-fb86AWPdJU5_JLV4jVM',
    appId: '1:777323726561:ios:dd43d86af9609b5b0f19a0',
    messagingSenderId: '777323726561',
    projectId: 'fleet-managment-7a764',
    storageBucket: 'fleet-managment-7a764.firebasestorage.app',
    iosClientId:
        '777323726561-hb7j2q0mel1biofg5a1diur35saqgknl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fleetApp',
  );
}
